### ISSUE TITLE
Nvidium is "***" and unusable in every way 

### ISSUE THREAD

**Issue by streetlegalb17** [NeDether/Rattler-Spore#11]
![nvidium](https://github.com/NeDether/Rattler-Spore/assets/151584342/8bbad898-e4dd-417c-a220-a0f296dca6f4)
Can't fabricate items that need it, or sell the supply I have

**Comment by NeDether** [comment]
This is a result of some of the later tier ores being unlocalized. 
I'll send out a patch when I have the time.
