### ISSUE TITLE
Create Placeable Drills on Colonized planets.

### ISSUE THREAD

**Issue by NeDether** [NeDether/Rattler-Spore#13]
I have no idea how the player is supposed to interact with them. Maybe a "selector" tool or try to make one of those buttons when you hover over it.

**Comment by M0ntherload** [comment]
i feel like this is required, because god damn a whole galactic empire and i have to do all the manual labor?? no way

**Comment by NeDether** [comment]
closing. replacing planetary factories with space stations for game flow.
